import { getTournamentSettings, getPlayers, getMatches, getBracket, getAnnouncements, getRules, getWinnerInformation } from '../services/data-service.js';

const page = document.body.dataset.page || 'home';
const links = [
  ['home','index.html','Home'],['players','players.html','Players'],['schedule','schedule.html','Schedule'],
  ['bracket','bracket.html','Bracket'],['results','results.html','Scores'],['rules','rules.html','Rules'],['announcements','announcements.html','Announcements']
];

function renderShell() {
  const header = document.querySelector('[data-site-header]');
  const footer = document.querySelector('[data-site-footer]');
  header.innerHTML = `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.html" aria-label="Tagalog Open home"><span class="brand-mark">TO</span><span>Tagalog Open</span></a><nav class="nav-links" id="site-nav" aria-label="Primary navigation">${links.map(([id,href,label])=>`<a href="${href}" ${id===page?'class="active" aria-current="page"':''}>${label}</a>`).join('')}</nav><button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="site-nav"><span></span><span></span><span></span></button></div></header>`;
  footer.innerHTML = `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="index.html"><span class="brand-mark">TO</span><span>Tagalog Open</span></a><p class="footer-copy">A premier Los Santos tennis tournament celebrating competition, community, and the city’s finest sporting talent.</p></div><div><div class="footer-title">Tournament</div><div class="footer-links"><a href="players.html">Players</a><a href="schedule.html">Schedule</a><a href="bracket.html">Bracket</a><a href="results.html">Scores & results</a></div></div><div><div class="footer-title">Information</div><div class="footer-links"><a href="rules.html">Official rules</a><a href="announcements.html">Announcements</a><a href="index.html#venue">Venue</a></div></div></div><div class="footer-bottom"><span>Presented by the Office of the Mayor, City of Los Santos</span><span>© 2026 Tagalog Open</span></div></div></footer>`;
  const toggle = document.querySelector('.menu-toggle');
  const nav = document.querySelector('.nav-links');
  toggle.addEventListener('click',()=>{ const open=nav.classList.toggle('open'); toggle.setAttribute('aria-expanded',String(open)); toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation'); document.body.classList.toggle('menu-open',open); });
  nav.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('menu-open');toggle.setAttribute('aria-expanded','false')});
}

const badge = status => `<span class="badge badge-${status.toLowerCase().replace(/\s+/g,'-')}">${status}</span>`;
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

function openModal(content) {
  const modal=document.querySelector('#detail-modal');
  if(!modal) return;
  modal.querySelector('.modal-panel').innerHTML=`<button class="modal-close" type="button" aria-label="Close details">×</button>${content}`;
  modal.hidden=false; document.body.style.overflow='hidden'; modal.querySelector('.modal-close').focus();
  const close=()=>{modal.hidden=true;document.body.style.overflow='';};
  modal.querySelector('.modal-close').addEventListener('click',close);
  modal.onclick=e=>{if(e.target===modal)close()};
  document.onkeydown=e=>{if(e.key==='Escape'&&!modal.hidden)close()};
}

async function renderHome(){
  const [settings,announcements,matches,winners]=await Promise.all([getTournamentSettings(),getAnnouncements(),getMatches(),getWinnerInformation()]);
  document.querySelector('[data-home]').innerHTML=`<section class="hero"><div class="container hero-grid"><div class="hero-copy"><div class="eyebrow">Presented by the Office of the Mayor</div><h1 class="display">Tagalog<br>Open</h1><p class="lead">${settings.tagline} Los Santos steps onto center court for three nights of precision, pressure, and championship tennis.</p><div class="hero-actions"><a class="button button-primary" href="schedule.html">View schedule <span>→</span></a><a class="button button-secondary" href="players.html">Meet the players</a></div></div><aside class="hero-card"><div class="hero-card-label">First serve in</div><div class="countdown" data-countdown aria-live="polite"></div><div class="hero-meta"><div><span class="hero-card-label">Dates</span><strong>${settings.displayDate}</strong></div><div><span class="hero-card-label">Venue</span><strong>Vespucci Tennis Club</strong></div></div></aside></div></section>
  <section class="section"><div class="container"><div class="stats-grid"><div class="stat"><strong>${settings.registeredCount}</strong><span>Players registered</span></div><div class="stat"><strong>${settings.capacity}</strong><span>Player capacity</span></div><div class="stat"><strong>${settings.totalMatches}</strong><span>Matches</span></div><div class="stat"><strong>${settings.prize}</strong><span>Prize purse</span></div></div></div></section>
  <section class="section section-soft"><div class="container"><div class="section-heading"><div><div class="eyebrow" style="color:var(--green-2)">City championship tennis</div><h2 class="section-title">The court belongs<br>to Los Santos</h2></div><p class="lead" style="color:#5e6b64">Sixteen competitors. One single-elimination bracket. Every rally moves one player closer to the city championship.</p></div><div class="cards-3"><article class="card"><div class="card-kicker">Registration</div><h3>${settings.registrationStatus}</h3><p class="muted">Four places remain. Registration closes August 9 or when the field reaches capacity.</p></article><article class="card"><div class="card-kicker">Format</div><h3>${settings.format}</h3><p class="muted">Best-of-three sets from the opening round through the championship final.</p></article><article class="card" id="venue"><div class="card-kicker">Venue</div><h3>${settings.location}</h3><p class="muted">Center Court and Court 2 host play across all three tournament nights.</p></article></div></div></section>
  <section class="section"><div class="container"><div class="section-heading"><div><div class="eyebrow">Pinned update</div><h2 class="section-title">Latest announcement</h2></div><a class="button button-secondary" href="announcements.html">All announcements</a></div><article class="announcement-feature"><div class="feature-label">Official<br>Notice</div><div class="feature-body"><div class="card-kicker">${announcements[0].category} · ${announcements[0].date}</div><h3>${announcements[0].title}</h3><p>${announcements[0].content}</p><a class="button button-primary" href="announcements.html">Read updates</a></div></article></div></section>
  <section class="section section-soft"><div class="container"><div class="section-heading"><div><div class="eyebrow" style="color:var(--green-2)">Center court</div><h2 class="section-title">Featured match</h2></div>${badge(matches.find(m=>m.status==='Live')?.status||'Upcoming')}</div>${featureMatch(matches.find(m=>m.status==='Live')||matches.find(m=>m.status==='Upcoming'))}</div></section>
  <section class="section"><div class="container"><div class="section-heading"><div><div class="eyebrow">The road ahead</div><h2 class="section-title">Tournament honors</h2></div><p class="muted">Revealed after championship night</p></div><div class="outcomes"><div class="card outcome-card ${winners.concluded?'':'tbd'}"><div class="outcome-icon">1</div><div class="eyebrow">Champion</div><h3>${winners.champion}</h3></div><div class="card outcome-card ${winners.concluded?'':'tbd'}"><div class="outcome-icon">2</div><div class="eyebrow">Runner-up</div><h3>${winners.runnerUp}</h3></div><div class="card outcome-card ${winners.concluded?'':'tbd'}"><div class="outcome-icon">★</div><div class="eyebrow">Tournament MVP</div><h3>${winners.mvp}</h3></div></div></div></section>
  <section class="section"><div class="container"><div class="section-heading"><div><div class="eyebrow">Explore</div><h2 class="section-title">Follow the tournament</h2></div></div><div class="cards-3"><a class="card quick-card" href="bracket.html"><div><div class="card-kicker">Progression</div><h3>Championship bracket</h3></div><span class="arrow">→</span></a><a class="card quick-card" href="results.html"><div><div class="card-kicker">Courtside</div><h3>Live scores & results</h3></div><span class="arrow">→</span></a><a class="card quick-card" href="rules.html"><div><div class="card-kicker">Official</div><h3>Tournament rules</h3></div><span class="arrow">→</span></a></div></div></section>`;
  startCountdown(settings);
}

function featureMatch(m){return `<article class="card"><div class="match-feature"><div><div class="competitor">${m.player1}</div><div class="muted">${m.round}</div></div><div class="versus">VS</div><div><div class="competitor">${m.player2}</div><div class="muted">${m.court} · ${m.time}</div></div></div></article>`}
function startCountdown(settings){const el=document.querySelector('[data-countdown]'); const tick=()=>{const now=Date.now(),start=new Date(settings.startDate).getTime(),end=new Date(settings.endDate).getTime();if(now>=end){el.innerHTML='<div class="count-message" style="grid-column:1/-1">Tournament Completed</div>';return}if(now>=start){el.innerHTML='<div class="count-message" style="grid-column:1/-1">Tournament In Progress</div>';return}let d=Math.max(0,start-now);const units=[['Days',Math.floor(d/86400000)],['Hours',Math.floor(d/3600000)%24],['Minutes',Math.floor(d/60000)%60],['Seconds',Math.floor(d/1000)%60]];el.innerHTML=units.map(([l,v])=>`<div class="count-unit"><strong>${String(v).padStart(2,'0')}</strong><span>${l}</span></div>`).join('')};tick();setInterval(tick,1000)}

async function renderPlayers(){const players=await getPlayers(),grid=document.querySelector('#players-grid'),search=document.querySelector('#player-search');const draw=()=>{const term=search.value.toLowerCase();const list=players.filter(p=>`${p.name} ${p.affiliation}`.toLowerCase().includes(term));document.querySelector('#player-count').textContent=`${list.length} player${list.length===1?'':'s'}`;grid.innerHTML=list.length?list.map(p=>`<article class="card player-card"><div class="player-top"><div class="avatar">${p.initials}</div><div class="seed">${p.seed?`Seed ${p.seed}`:'Unseeded'}</div></div><h3>${p.name}</h3><div class="muted">${p.affiliation}</div><div class="card-footer">${badge(p.registration)}<button class="text-button" data-player="${p.id}">View profile →</button></div></article>`).join(''):`<div class="empty-state" style="grid-column:1/-1"><strong>No players found</strong>Try another name or organization.</div>`;grid.querySelectorAll('[data-player]').forEach(btn=>btn.onclick=()=>{const p=players.find(x=>x.id===btn.dataset.player);openModal(`<div class="avatar">${p.initials}</div><h2 class="modal-title">${p.name}</h2><div class="muted">${p.affiliation}</div><div class="detail-grid"><div class="detail"><small>Seed</small><strong>${p.seed||'Unseeded'}</strong></div><div class="detail"><small>Status</small><strong>${p.status}</strong></div><div class="detail"><small>Hometown</small><strong>${p.hometown}</strong></div><div class="detail"><small>Plays</small><strong>${p.handedness}</strong></div></div><p>${p.bio}</p>`)});};search.addEventListener('input',draw);draw()}

async function renderSchedule(){const matches=await getMatches();const controls=['round','status','court','search'];const els=Object.fromEntries(controls.map(x=>[x,document.querySelector(`#filter-${x}`)])); const uniq=k=>[...new Set(matches.map(m=>m[k]))];els.round.innerHTML='<option value="">All rounds</option>'+uniq('round').map(x=>`<option>${x}</option>`).join('');els.status.innerHTML='<option value="">All statuses</option>'+uniq('status').map(x=>`<option>${x}</option>`).join('');els.court.innerHTML='<option value="">All courts</option>'+uniq('court').map(x=>`<option>${x}</option>`).join('');const draw=()=>{const list=matches.filter(m=>(!els.round.value||m.round===els.round.value)&&(!els.status.value||m.status===els.status.value)&&(!els.court.value||m.court===els.court.value)&&`${m.player1} ${m.player2}`.toLowerCase().includes(els.search.value.toLowerCase()));document.querySelector('#schedule-body').innerHTML=list.map(m=>`<tr><td>${m.displayDate}<br><span class="muted">${m.time}</span></td><td>${m.court}</td><td>${m.round}</td><td class="name-cell">${m.player1}<br><span class="muted">vs ${m.player2}</span></td><td>${badge(m.status)}</td></tr>`).join('');document.querySelector('#schedule-mobile').innerHTML=list.map(m=>`<article class="mobile-match"><div class="mobile-match-head"><strong>${m.displayDate} · ${m.time}</strong>${badge(m.status)}</div><div class="mobile-match-players">${m.player1}<br><span class="muted">vs</span> ${m.player2}</div><div class="mobile-match-meta"><span>${m.round}</span><span>${m.court}</span></div></article>`).join('');document.querySelector('#schedule-empty').hidden=!!list.length;document.querySelector('.table-wrap').style.visibility=list.length?'visible':'hidden'};Object.values(els).forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',draw));draw()}

async function renderBracket(){const rounds=await getBracket();document.querySelector('#bracket').innerHTML=rounds.map((r,i)=>`<section class="bracket-round ${i===rounds.length-1?'champion-round':''}"><h3>${r.name}</h3><div class="round-matches">${r.matches.map((m,j)=>`<article class="bracket-match" aria-label="${r.name} match ${j+1}">${m.slice(0,2).filter(Boolean).map(name=>`<div class="bracket-player ${m[2]===name?'winner':''} ${name==='TBD'?'tbd':''}"><span>${name}</span>${m[2]===name?'<span>✓</span>':''}</div>`).join('')}</article>`).join('')}</div></section>`).join('')}

async function renderResults(){const matches=await getMatches(),live=matches.filter(m=>m.status==='Live'),done=matches.filter(m=>m.status==='Completed');const card=m=>`<article class="result-card"><div class="result-head"><span>${m.round} · ${m.court}</span>${badge(m.status)}</div><div class="score-line ${m.winner===m.player1?'winner':''}"><span>${m.player1}</span><strong>${m.score.split(', ')[0]||'—'}</strong></div><div class="score-line ${m.winner===m.player2?'winner':''}"><span>${m.player2}</span><strong>${m.status==='Live'?'Current':m.winner===m.player2?'Winner':'Final'}</strong></div><div class="result-foot"><span>${m.displayDate} · ${m.time}</span><button class="text-button" data-match="${m.id}">Match details →</button></div></article>`;const render=(id,list,label)=>{const el=document.querySelector(id);el.innerHTML=list.length?list.map(card).join(''):`<div class="empty-state" style="grid-column:1/-1"><strong>No ${label}</strong>Check back when play gets underway.</div>`};render('#live-results',live,'live matches');render('#completed-results',done,'completed results');document.querySelectorAll('[data-match]').forEach(btn=>btn.onclick=()=>{const m=matches.find(x=>x.id===btn.dataset.match);openModal(`<div>${badge(m.status)}</div><h2 class="modal-title">${m.player1}<br><span class="muted">vs</span> ${m.player2}</h2><div class="detail-grid"><div class="detail"><small>Score</small><strong>${m.score}</strong></div><div class="detail"><small>Winner</small><strong>${m.winner||'In progress'}</strong></div><div class="detail"><small>Round</small><strong>${m.round}</strong></div><div class="detail"><small>Court</small><strong>${m.court}</strong></div></div><p>${m.note}</p>`)});document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>{t.classList.toggle('active',t===tab);t.setAttribute('aria-selected',String(t===tab))});document.querySelectorAll('.tab-panel').forEach(panel=>panel.hidden=panel.id!==tab.dataset.tab)})}

async function renderRules(){const [rules,settings]=await Promise.all([getRules(),getTournamentSettings()]);document.querySelector('#rules-updated').textContent=settings.lastUpdated;document.querySelector('#rules-list').innerHTML=rules.map((r,i)=>`<article class="accordion ${i===0?'open':''}"><h2><button class="accordion-trigger" type="button" aria-expanded="${i===0}" aria-controls="rule-${i}"><span>${r.title}</span><span>+</span></button></h2><div class="accordion-content" id="rule-${i}" ${i===0?'':'hidden'}><p>${r.content}</p></div></article>`).join('');document.querySelectorAll('.accordion-trigger').forEach(btn=>btn.onclick=()=>{const item=btn.closest('.accordion'),content=item.querySelector('.accordion-content'),open=item.classList.toggle('open');content.hidden=!open;btn.setAttribute('aria-expanded',String(open))})}

async function renderAnnouncements(){const list=(await getAnnouncements()).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.iso.localeCompare(a.iso));document.querySelector('#announcement-list').innerHTML=list.length?list.map(a=>`<article class="announcement-card ${a.pinned?'pinned':''}"><div class="announcement-meta">${a.pinned?'<span class="pin-label">★ Pinned</span>':''}<span>${a.date}</span><span>•</span><span>${a.category}</span></div><h2>${a.title}</h2><p>${a.content}</p></article>`).join(''):`<div class="empty-state"><strong>No announcements yet</strong>Official tournament updates will appear here.</div>`}

renderShell();
const renderers={home:renderHome,players:renderPlayers,schedule:renderSchedule,bracket:renderBracket,results:renderResults,rules:renderRules,announcements:renderAnnouncements};
renderers[page]?.().catch(error=>{console.error(error);const main=document.querySelector('main');main.insertAdjacentHTML('beforeend','<div class="container section"><div class="empty-state"><strong>Unable to load this page</strong>Please refresh and try again.</div></div>')});
